# Generated by Django 4.1.4 on 2022-12-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_contact_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_data',
        ),
    ]
