# Generated by Django 4.1.4 on 2022-12-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
