# Generated by Django 4.1.4 on 2022-12-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('emmail', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('coverletter', models.CharField(max_length=1000)),
            ],
        ),
    ]
