# Generated by Django 4.1.4 on 2022-12-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_application_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='CV',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='Application/'),
        ),
    ]
