# Generated by Django 4.1.4 on 2022-12-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_application_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='emmail',
            new_name='email',
        ),
    ]
